export default [
  {
    id: 17,
    name: "Косметолог",
    created_at: "2019-10-11 12:45:29",
    updated_at: "2019-10-11 12:45:29",
    slug: "beautician",
    description:
      "Косметология - это то, что поможет Вам самым эффективным образом избавится от дефектов кожи лица и тела, дать ей эффект омоложения и ухоженности, дополнить свой образ сногсшибательным видом, чтобы Вы выглядели превосходно по всем параметрам. В соответствии с желаемым результатом меняется уровень травматичности и хирургического вмешательства. От банального ухода за телом, до существенных изменений и это всё, для пути к идеальному образу. ",
    short_name: "Косметолог",
    sub_services: [
      {
        id: 17,
        name: "Эстетическая косметология",
        service_id: 17,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "aesthetic-cosmetology",
        description:
          "Стандартный уход за кожей и телом, имеющий минимальную травматичность. Способ, для поддержания тонуса здоровья кожи и тела с минимальным вмешательством",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-17.svg",
        short_name: null,
      },
      {
        id: 19,
        name: "Аппаратная косметология",
        service_id: 17,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "hardware-cosmetology",
        description:
          "Ухаживайте за здоровьем лица самыми современными методами, которые самым эффективным методом справляются с омолаживающими и оздоравливающими задачами без каких либо болевых ощущений ",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-19.svg",
        short_name: null,
      },
      {
        id: 18,
        name: "Инъекционная косметология",
        service_id: 17,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "injection-cosmetology",
        description:
          "Улучшение внешнего вида с помощью препарата, который поможет “проапгрейдить” Вас, для достижения идеального результата",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-18.svg",
        short_name: null,
      },
    ],
  },
  {
    id: 19,
    name: "Брови и ресницы",
    created_at: "2019-10-11 12:45:29",
    updated_at: "2019-10-11 12:45:29",
    slug: "eyebrows-and-eyelashes",
    description:
      "Брови и ресницы - это важная черта в образе любой девушки. Любой образ сопровождается разными формами и цветами этих двух составляющих женской красоты. Дополните свой образ здоровыми и привлекательными бровями и ресницами. ",
    short_name: "Брови и ресницы",
    sub_services: [
      {
        id: 36,
        name: "Уход за ресницами",
        service_id: 19,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "eyelash-care",
        description:
          "Здоровые ресницы - красивые ресницы. Об этом знает любая девушка, вне зависимости от типа предпочитаемых ресничек",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-36.svg",
        short_name: null,
      },
      {
        id: 35,
        name: "Уход за бровями",
        service_id: 19,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "eyebrow-care",
        description:
          "“Бровки домиком…” Сделайте ваши брови выразительными и поверьте, Вас будет тяжело не заметить  ",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-35.svg",
        short_name: null,
      },
    ],
  },
  {
    id: 21,
    name: "Мужские парикмахерские услуги (Барберы)",
    created_at: "2019-10-11 12:45:29",
    updated_at: "2019-10-11 12:45:29",
    slug: "mens-hairdressing-services-barbers",
    description:
      "Не важно кто Вы и чем Вы занимаетесь, чтобы выглядеть привлекательно Вам нужна хорошая стрижка и ухоженная борода. Создайте мужественный образ и сразите “наповал” любую представительницу противоположного пола, даже если это деловой партнер. Хорошая стрижка и ухоженная борода - залог успешного мужчины. \n",
    short_name: "Барберы",
    sub_services: [
      {
        id: 56,
        name: "Укладка волос",
        service_id: 21,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "hair-styling",
        description:
          "Уложите Ваши волосы так, чтобы они идеально подчеркивали Вашу прическу, форму головы и стиль. Будьте модным и стильным, это придаёт уверенности в себе ",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-55.svg",
        short_name: null,
      },
      {
        id: 53,
        name: "Мужская стрижка",
        service_id: 21,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "mens-haircut",
        description:
          "Модная стрижка, неотъемлемый атрибут современного мужчины. Сделайте нужную Вам прическу, подходящую под Ваш стиль и вкус и Вы будете самым непревзойденным и эффектным мужчиной в любом коллективе ",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-52.svg",
        short_name: null,
      },
      {
        id: 55,
        name: "Десткая стрижка",
        service_id: 21,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "baby-haircut",
        description:
          "Сделайте стрижку своему подрастающему мужчине, в зависимости его предпочтений, выделите его индивидуальность и Ваш ребенок будет выглядеть “на все сто!”",
        image:
          "https://imgdev.beautylinks.com/sub-services/sub-service-54-2.svg",
        short_name: null,
      },
      {
        id: 54,
        name: "Уход за бородой",
        service_id: 21,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "beard-care",
        description: "Уделите должное внимание “красавице-бороде”",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-55.svg",
        short_name: null,
      },
    ],
  },
  {
    id: 22,
    name: "Удаление волос",
    created_at: "2019-10-11 12:45:29",
    updated_at: "2019-10-11 12:45:29",
    slug: "depilation",
    description:
      "У девушек крайне чувствительная кожа и это знают абсолютно все. Как правило, удаление волос в домашних условиях чревато раздражением кожи,жесткой черной щетиной и очень быстрым ростом новых волос. Так сколько же еще можно страдать? Все,что нужно сделать,это обратиться к профессионалу и выбрать подходящий способ удаления из нижеперечисленных!",
    short_name: "Удаление волос",
    sub_services: [
      {
        id: 61,
        name: "Электроэпиляция",
        service_id: 22,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "electrology",
        description:
          "Перманентное удаление волос за счёт небольшого разряда электричества",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-59.svg",
        short_name: null,
      },
      {
        id: 63,
        name: "Бикини-дизайн",
        service_id: 22,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "bikini-design",
        description:
          "Комплекс услуг, включающий в себя фигурную стрижку с элементами депиляции, окраску волос, а также украшение прически декоративными элементами.",
        image:
          "https://imgdev.beautylinks.com/sub-services/sub-service-61-2.svg",
        short_name: null,
      },
      {
        id: 58,
        name: "Лазерная Эпиляция",
        service_id: 22,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "laser-hair-removal",
        description:
          "Безболезненное удаление волос лазером,Вы на несколько лет забудете о постоянном бритье, раздражениях , потерянном времени и вросших волосах",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-57.svg",
        short_name: null,
      },
      {
        id: 62,
        name: "Фотоэпиляция",
        service_id: 22,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "photoepilation",
        description:
          "Удаление нежелательных волос при помощи узкого спектра световой волны,избавление от растительности длительное время",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-60.svg",
        short_name: null,
      },
      {
        id: 57,
        name: "Удаление Волос Воском (Восковая Эпиляция)",
        service_id: 22,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "waxing-hair-removal-waxing",
        description:
          "Восковая депиляция - это наилучшая альтернатива классической бритве,до месяца наслаждения бархатистой кожей",
        image:
          "https://imgdev.beautylinks.com/sub-services/sub-service-56-2.svg",
        short_name: null,
      },
      {
        id: 59,
        name: "Шугаринг",
        service_id: 22,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "shugaring",
        description:
          "Гипоаллергенный способ депиляции, результат продержится до 3-х недель",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-61.svg",
        short_name: null,
      },
      {
        id: 60,
        name: "Депиляция Нитью",
        service_id: 22,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "hair-removal",
        description:
          "Корейская процедура удаления лишних волосков с помощью нити",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-58.svg",
        short_name: null,
      },
    ],
  },
  {
    id: 20,
    name: "Уход за телом",
    created_at: "2019-10-11 12:45:29",
    updated_at: "2019-10-11 12:45:29",
    slug: "body-care",
    description:
      "Помимо эстетической красоты и восторженных взглядов противоположного пола, ваша кожа - важный орган отвечающий за ваше самочувствие, здоровье и настроение. \nСтройное подтянутое тело со здоровой кожей всегда будет привлекать внимание и делать человека уверенным. В этом разделе представлены специалисты, которые не просто позаботятся о вашем здоровье, но и поднимут настроение и уверенность в себе!",
    short_name: "Уход за телом",
    sub_services: [
      {
        id: 43,
        name: "Кавитация",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "cavitation",
        description:
          "Легкое и безболезненное избавление от жировых отложений без каких-либо операций",
        image:
          "https://imgdev.beautylinks.com/sub-services/sub-service-42-2.svg",
        short_name: null,
      },
      {
        id: 40,
        name: "Скрабирование и Пилинг Тела",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "body-scrub-and-peeling",
        description:
          "Повышение эластичности и упругости кожи,придание ей бархатистости и мягкости\n",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-40.svg",
        short_name: null,
      },
      {
        id: 37,
        name: "Массаж",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "massage",
        description:
          "От лечебного и оздоровительного до расслабляющего и общего",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-37.svg",
        short_name: null,
      },
      {
        id: 44,
        name: "Миостимуляция Тела",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "body-miostimulation",
        description:
          "Избавление от лишнего жира и целлюлита, улучшение состояния и внешнего вида кожи в короткие сроки",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-43.svg",
        short_name: null,
      },
      {
        id: 38,
        name: "Обертывание",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "wrapping",
        description:
          "Ускорение кровообращения, выведение шлаков и токсинов из организма, отличная помощь при похудении",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-38.svg",
        short_name: null,
      },
      {
        id: 52,
        name: "Интимная Косметология",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "intimate-cosmetology",
        description:
          "Специалисты интимной косметологии работают над эстетическим видом интимной зоны",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-51.svg",
        short_name: null,
      },
      {
        id: 39,
        name: "Бани, Сауны (Водные Процедуры)",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "baths-saunas-water-treatments",
        description: "Энергетическая и физическая “перезагрузка” организма",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-39.svg",
        short_name: null,
      },
      {
        id: 49,
        name: "Комплексный Уход за Телом",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "comprehensive-body-care",
        description:
          "Отличная возможность за 1 поход совместить приятное с полезным",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-48.svg",
        short_name: null,
      },
      {
        id: 41,
        name: "Мезотерапия",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "mesotherapy",
        description:
          "Омоложение кожного покрова лица, повышение плотности и упругости кожи",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-41.svg",
        short_name: null,
      },
      {
        id: 42,
        name: "Карбокситерапия",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "carboxytherapy",
        description:
          "Лечение возрастных изменений структуры кожи путём воздействия углекислым газом",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-41.svg",
        short_name: null,
      },
      {
        id: 50,
        name: "Плацентотерапия",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "placent-therapy",
        description:
          "Разглаживание морщин,\nзамедление процессов старения,проявление эффекта лифтинга.",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-49.svg",
        short_name: null,
      },
      {
        id: 47,
        name: "Инъекционное Похудение",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "injection-slimming",
        description:
          "Уменьшение жировых отложений;\nформа и контуры тела приближаются к идеалу",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-46.svg",
        short_name: null,
      },
      {
        id: 45,
        name: "RF-лифтинг",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "rf-lifting",
        description:
          "Разглаживание морщин, подтягивание овала лица и повышение эластичности кожи",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-44.svg",
        short_name: null,
      },
      {
        id: 51,
        name: "SPA-процедуры",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "spa-treatments",
        description:
          "Снятие стресса и напряжения.Как насчет того, чтобы попасть на “седьмое небо от счастья” ?",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-50.svg",
        short_name: null,
      },
      {
        id: 48,
        name: "Аппаратная Косметология",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "hardware-cosmetology",
        description:
          "Омоложение, коррекция силуэта, избавление от растяжек, целлюлита или шрамов, возрастных проблем кожи лица.",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-47.svg",
        short_name: null,
      },
      {
        id: 46,
        name: "Плазмолифтинг",
        service_id: 20,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "plasmolifting",
        description:
          "Омоложение кожного покрова лица, повышение плотности и упругости кожи",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-45.svg",
        short_name: null,
      },
    ],
  },
  {
    id: 16,
    name: "Уход за ногтями",
    created_at: "2019-10-11 12:45:29",
    updated_at: "2019-10-11 12:45:29",
    slug: "nail-care",
    description:
      "Ухоженные руки — визитная карточка женщины. Красивый маникюр, аккуратные кутикулы и нежная чистая кожа расскажут о своей хозяйке может даже больше, чем она сама. Безупречный маникюр, аккуратные ногти – сегодня это необходимые атрибуты красоты и залог успеха, в том числе и в мире бизнеса. Уход за ногтями - это не только стрижка ногтей. Это понятие включает в себя услуги по комплексному уходу за руками. Ну и про ваши ножки мы тоже не забыли!",
    short_name: "Уход за ногтями",
    sub_services: [
      {
        id: 11,
        name: "SPA Маникюр и Педикюр",
        service_id: 16,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "spa-manicure-and-pedicure",
        description: "Комплексный уход за руками и ногами",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-11.svg",
        short_name: null,
      },
      {
        id: 9,
        name: "Маникюр",
        service_id: 16,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "manicure",
        description:
          "С помощью профессионального маникюра можно:\n- восстановить кутикулу;\n- укрепить ногтевую пластину;\n- подарить коже сияние и нежность.\nИ это только самая малость того,на что способны мастера,представленные на платформе!",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-09.svg",
        short_name: null,
      },
      {
        id: 15,
        name: "Комплексные Услуги по Уходу за Ногтями",
        service_id: 16,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "comprehensive-nail-care-services",
        description:
          "Комплексные услуги дают возможность за одну процедуру привести в порядок руки или ноги, или даже всё вместе. Таким образом вы значительно экономите своё время!",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-15.svg",
        short_name: null,
      },
      {
        id: 13,
        name: "Дизайн Ногтей",
        service_id: 16,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "nail-design",
        description:
          "Превратите ваши руки в настоящее произведение искусства,подчеркните свою индивидуальность и привлеките внимание окружающих к своим рукам",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-13.svg",
        short_name: null,
      },
      {
        id: 14,
        name: "Покрытие Лаком",
        service_id: 16,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "varnish-coating",
        description:
          "Большой выбор цветов и оттенков лака премиум-класса. Возможность сделать дизайн любой сложности.",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-14.svg",
        short_name: null,
      },
      {
        id: 16,
        name: "Подология (Лечение Ногтей)",
        service_id: 16,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "podology-nail-treatment",
        description: "Лечение заболеваний стоп, ногтей и кожи ног",
        image:
          "https://imgdev.beautylinks.com/sub-services/sub-service-16-2.svg",
        short_name: null,
      },
      {
        id: 10,
        name: "Педикюр",
        service_id: 16,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "pedicure",
        description:
          "Педикюр сохранит красоту ваших ног и поможет избежать различных заболеваний",
        image:
          "https://imgdev.beautylinks.com/sub-services/sub-service-10-2.svg",
        short_name: null,
      },
      {
        id: 12,
        name: "Наращивание Ногтей",
        service_id: 16,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "nail-extensions",
        description:
          "Мастера с лёгкостью подберут необходимую форму и длину ногтей под Вас и ваши личные предпочтения, наращивание любого вида",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-12.svg",
        short_name: null,
      },
    ],
  },
  {
    id: 15,
    name: "Уход за волосами",
    created_at: "2019-10-11 12:45:29",
    updated_at: "2019-10-11 12:45:29",
    slug: "hair-care",
    description:
      "Сегодня как никогда актуален превосходный внешний вид. Для его поддержания требуется регулярный уход за волосами, ведь именно прическа является одним из определяющих факторов внешнего вида. Стильная и аккуратная прическа не менее важна, чем красивый наряд и модные аксессуары. Однако следовать актуальным тенденциям индустрии моды не всегда просто, поскольку они очень быстро меняются, именно поэтому в этом разделе представлены профессионалы своего дела, которые помогут вам идти в ногу со временем,получая от этого процесса максимум удовольствия!",
    short_name: "Уход за волосами",
    sub_services: [
      {
        id: 6,
        name: "Наращивание Волос",
        service_id: 15,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "hair-extension",
        description:
          "Увеличение объема и длины волос,возможность кардинального преображения всего за несколько часов",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-06.svg",
        short_name: null,
      },
      {
        id: 7,
        name: "Плетение Кос и Жгутиков",
        service_id: 15,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "weaving-braids-and-flagella",
        description:
          "Одной из причесок, над которой не властна мода, является коса. Плетение, выполненное на волосах, способно добавить женственности в любой образ",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-07.svg",
        short_name: null,
      },
      {
        id: 1,
        name: "Лечение волос и кожи головы",
        service_id: 15,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "hair-scalp-treatment",
        description:
          "Устранение выпадения волос и их укрепление,лечение заболеваний кожи головыУстранение выпадения волос и их укрепление,лечение заболеваний кожи головы",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-03.svg",
        short_name: null,
      },
      {
        id: 3,
        name: "Окрашивание Волос",
        service_id: 15,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "hair-coloring",
        description:
          "Здесь представлены опытные мастера-колористы,всё от однотонного окрашивания до балаяжа",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-01.svg",
        short_name: null,
      },
      {
        id: 4,
        name: "Парикмахеры (Стрижки и Укладки)",
        service_id: 15,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "hairdressers-haircuts-and-styling",
        description:
          "Прическа — выражение вашей индивидуальности и внутреннего мира. Правильно подобранная стрижка и укладка являются главными критериями стильного образа.",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-04.svg",
        short_name: null,
      },
      {
        id: 2,
        name: "Текстурирование Волос (Завивка)",
        service_id: 15,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "hair-texturing-waving",
        description:
          "Все от мега-фиксации до легкости и воздушности ваших локонов,объем и укладка любой сложности",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-02.svg",
        short_name: null,
      },
      {
        id: 5,
        name: "Детский парикмахер",
        service_id: 15,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "childrens-hairdresser",
        description:
          "Мастера детских стрижек постараются сделать так, чтобы ваш ребенок не проронил ни слезинки во время стрижки,а получил истинное удовольствие ",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-05.svg",
        short_name: null,
      },
      {
        id: 8,
        name: "Дреды",
        service_id: 15,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "dreadlocks",
        description: "Для желающих ярко самовыражаться",
        image:
          "https://imgdev.beautylinks.com/sub-services/sub-service-08-2.svg",
        short_name: null,
      },
    ],
  },
  {
    id: 18,
    name: "Макияж",
    created_at: "2019-10-11 12:45:29",
    updated_at: "2019-10-11 12:45:29",
    slug: "makeup",
    description:
      "«Не бывает некрасивых женщин. Бывают равнодушные к себе и косметике». \nEstee Lauder \n\nВ своем современном виде, макияж имеет десятки вариаций и предназначений, на каждый случай жизни.  \n",
    short_name: "Макияж",
    sub_services: [
      {
        id: 24,
        name: "Макияж для Особых Случаев",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "makeup-for-special-occasions",
        description:
          "Подборка мастеров, которые сделают макияж специально для случая, в котором не подойдёт стандартный подход. Произведите фурор, где бы вы ни были",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-24.svg",
        short_name: null,
      },
      {
        id: 25,
        name: "Бесконтактный Макияж (Аэромакияж)",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "contactless-makeup-aerial-makeup",
        description:
          "Выход для тех, кто устал от обыденного нанесения макияжа, и ищет что-то нового. Он стойкий, и не требует постоянных поправок, но и одновременно не забивает поры, не вызывая раздражения, а самое главное, в разы сокращает затраты Вашего драгоценного времени",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-25.svg",
        short_name: null,
      },
      {
        id: 21,
        name: "Вечерний Макияж",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "evening-makeup",
        description:
          "Впереди вечеринка или корпоратив? Не проблема, задай себе нужный образ, дабы быть незабываемой на любом мероприятии",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-21.svg",
        short_name: null,
      },
      {
        id: 29,
        name: "Детский Макияж",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "childrens-makeup",
        description:
          "Ребёнок - хрупкое создание, и он требует хрупкого обращения. Детский макияж - это щепетильное дело и оно требует особых навыков с помощью использования исключительно натуральной косметики, для создания выразительного образа вашего ребёнка, чтобы он выглядел на все сто не важно где, будь то утренник, первый-последний звонок, праздник или же просто семейная фотосессия",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-29.svg",
        short_name: null,
      },
      {
        id: 34,
        name: "Nude-макияж",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "nude-makeup",
        description:
          "Подчеркните свою уникальность, используя естественные цвета, дабы Ваша натуральная красота имела чёткие очертания. Макияж является монохромным",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-34.svg",
        short_name: null,
      },
      {
        id: 28,
        name: "Мужской Макияж",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "male-makeup",
        description:
          "Думали макияж только для женского пола? Ну уж нет, мужчина тоже может скрыть какие либо увечья, раздражения и покраснения либо просто омолодить своё лицо, в наше время, это вполне нормальное явление.",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-28.svg",
        short_name: null,
      },
      {
        id: 32,
        name: "Создание Образа",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "creating-an-image",
        description:
          "Процесс макияжа по Вашим наработкам с помощью мастера. Воплотите самые смелые идеи",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-32.svg",
        short_name: null,
      },
      {
        id: 22,
        name: "Свадебный Макияж",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "wedding-makeup",
        description:
          "Подготовьте себя к одному из самых важных событий в Вашей жизни и оно запомниться в Ваших моментах наилучшим образом",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-22.svg",
        short_name: null,
      },
      {
        id: 30,
        name: "Лифтинг-макияж",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "lifting-makeup",
        description:
          "Создайте эффект омоложения посредством подтягивания контуров лица, визуального удаления морщин и обвислостей",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-30.svg",
        short_name: null,
      },
      {
        id: 23,
        name: "Макияж для Фотосессии",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "makeup-for-photoshoot",
        description:
          "Макияж, который поможет Вам выглядеть на фотосессии максимально фотогенично. Даешь качественную картинку!",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-23.svg",
        short_name: null,
      },
      {
        id: 31,
        name: "Консультация по Макияжу",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "makeup-consulting",
        description:
          "Проконсультируйтесь с мастером по-поводу наилучшего подбора цветов, тонов и косметики под ваш тип кожи и форму лица. Откройте наиболее соответствующий Вам образ.",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-31.svg",
        short_name: null,
      },
      {
        id: 33,
        name: "Коктейльный Макияж",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "cocktail-makeup",
        description:
          "Апероль, ещё апероль, а какая музыка! Ух, удалась вечеринка! Подготовьтесь к коктейльной вечеринке надлежащим образом. ",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-33.svg",
        short_name: null,
      },
      {
        id: 26,
        name: "Экспресс-макияж",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "express-makeup",
        description:
          "Для тех, кто действительно спешит, экспресс макияж подойдет идеально. Украсьте свой образ минимумом косметических средств и соответственно минимумом затрат времени. Поспеши! ",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-26.svg",
        short_name: null,
      },
      {
        id: 27,
        name: "Аквагрим",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "face-painting",
        description:
          "Создайте уникальный образ с помощью техники аквагрима. Идеально для карнавала или костюмированной вечеринки",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-27.svg",
        short_name: null,
      },
      {
        id: 20,
        name: "Дневной макияж",
        service_id: 18,
        created_at: "2019-10-11 12:45:33",
        updated_at: "2019-10-11 12:45:33",
        default_duration: 60,
        slug: "day-makeup",
        description:
          "Нанесение повседневного легкого макияжа, для работы в офисе, учебы или деловой поездки. Минимализм - залог успеха.   \n",
        image: "https://imgdev.beautylinks.com/sub-services/sub-service-20.svg",
        short_name: null,
      },
      {
        id: 64,
        name: "Перманентный макияж",
        service_id: 18,
        created_at: "2020-05-21 10:50:59",
        updated_at: "2020-05-21 10:50:56",
        default_duration: 60,
        slug: "permanent-makeup",
        description: null,
        image: "https://img.beautylinks.com/sub-services/sub-service-64.svg",
        short_name: null,
      },
    ],
  },
];
